package com.example.demo.user.enums;

public enum Step {
    GET_PHONE_UZ, GET_DATA_UZ, GET_PROFESSION_UZ,
    GET_NAME_RU, GET_PHONE_RU, GET_DATA_RU, GET_PROFESSION_RU,
    GET_NAME_UZ, CLAIM_UZ, CLAIM_RU, MAIN_UZ, MAIN_RU,
    NONE, EXP_UZ, EXP_RU, GET_LAN_UZ, GET_LAN_RU
}
